# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02f3ff580b9b823e1ef53d4c766ce03b1fabff4607c420592dd187492484206426380fd079d76a9bad881901453d131b35ccad0904303503cbd7d7af8095d501

test:
  secret_key_base: 0fb91ae92ad5aa79fba007810e60d0127012193165623aa137b1e7a332bcdb43ee81279824d8e8fa649b23e6dcef271375cb9077a456a527ac67eed81104e93e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
